TypeError: 'null' is not an object (evaluating 'g.tagName')
`TypeError: 'null' is not an object (evaluating 'g.tagName')`

It was throwing above exception in our min file. Would be very much helpful to update to latest version if you can pull it.